name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow for tags matching this pattern

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Build PlatformIO project
        run: pio run

      - name: List build directory
        run: ls -R .pio/build/upesy_wroom

      - name: Create version.json
        run: |
          echo '{ "version": "1.0.1", "url": "https://github.com/${{ github.repository }}/releases/latest/download/firmware.bin" }' > version.json

      - name: Create Release
        uses: softprops/action-gh-release@v1 # Use a common release action
        with:
          tag_name: ${{ github.ref }} # Uses the current tag
          files: |
            .pio/build/upesy_wroom/firmware.bin
            version.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token
