name: Build and Release

on:
  push:
    branches:
      - main # Cambia esto según la rama que desees usar para las compilaciones automáticas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar PlatformIO
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      # Paso 3: Construir el proyecto PlatformIO
      - name: Build PlatformIO project
        run: pio run

      # Paso 4: Listar archivos en el directorio de compilación
      - name: List build directory
        run: ls -R .pio/build/upesy_wroom

      # Paso 5: Crear version.json
      - name: Create version.json
        run: |
          echo '{ "version": "1.0.1", "url": "https://github.com/${{ github.repository }}/releases/latest/download/firmware.bin" }' > version.json

      # Paso 6: Crear una nueva Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.1
          files: |
            .pio/build/upesy_wroom/firmware.bin  # Asegúrate de que este archivo exista
            version.json
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }} # Usa tu token personal
