name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Solo ejecuta el flujo de trabajo para etiquetas que sigan este patrón

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Build PlatformIO project
        run: pio run

      - name: List build directory
        run: ls -R .pio/build/upesy_wroom

      - name: Create version.json
        run: |
          echo '{ "version": "1.0.1", "url": "https://github.com/${{ github.repository }}/releases/latest/download/firmware.bin" }' > version.json

      - name: Create Release
        uses: release-tag-action@v1
        with:
          tag: ${{ github.ref }} # Utiliza la etiqueta actual
          files: |
            .pio/build/upesy_wroom/firmware.bin
            version.json
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }} # Usa tu token personal
